[package]
name = "russh"
version = "0.1.0"
authors = ["Pascal Friederich <paukul@gmail.com>"]

[lib]
name = "russh"
path = "src/lib.rs"

[[bin]]
name = "russh"
path = "src/bin.rs"

[dependencies]
log = "~0.4.1"
env_logger = "~0.5.10"
failure = "*"